name = "emnehjelper-cache"
main = "src/index.js"
compatibility_date = "2026-06-13"

[vars]
ALLOWED_INSTITUTE = "ntnu"

[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = true
